
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benakun_app
    depends_on:
      - tarantool1
      - clickhouse1
      - mailhog1
    env_file:
      - .env
    environment:
      TARANTOOL_HOST: tarantool1
      TARANTOOL_PORT: 3301
      CLICKHOUSE_HOST: clickhouse1
      CLICKHOUSE_PORT: 9000
      MAILHOG_HOST: mailhog1
      MAILHOG_PORT: 1025
      WEB_PORT: 1235
      WEB_PROTO_DOMAIN: http://localhost:1235
      UPLOAD_DIR: /app/uploads
    ports:
      - "1235:1235"
    volumes:
      - benakun_uploads:/app/uploads
    restart: unless-stopped

  tarantool1:
    image: tarantool/tarantool:2.11.2
    container_name: benakun_tarantool
    environment:
      TARANTOOL_USER_NAME: "benakunT"
      TARANTOOL_USER_PASSWORD: "benakunPT"
      TT_READAHEAD: '1632000' # 10x
      TT_VINYL_MEMORY: '268435456' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
      TT_MEMTX_MEMORY: '268435456' # 1x
      TT_VINYL_PAGE_SIZE: '8192' # 1x
    volumes:
      - tarantool_data:/var/lib/tarantool
    ports:
      - "3302:3301"

  clickhouse1:
    image: clickhouse/clickhouse-server:23.11.2.11
    # previously: 23.4.2.11
    # next: 24.1
    container_name: benakun_clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_USER: "benakunC"
      CLICKHOUSE_PASSWORD: "benakunPC"
      CLICKHOUSE_DB: "default"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  mailhog1:
    image: mailhog/mailhog
    container_name: benakun_mailhog
    ports:
      - "1026:1025"
      - "8026:8025"

volumes:
  tarantool_data:
  clickhouse_data:
  benakun_uploads: